### ISSUE TITLE
Keyword list only

### ISSUE THREAD

**Issue by Mayalexx** [arzdou/botXiv#3]
If people starts to contribute to that list, it can become quite long at some point and difficult to read (it already is lol).

- Some ordering could be helpful. (alphabetical in a category? See next point.)
- One could use some data structure too, for instance:

```
Authors:
     author 0
     author 1

Groups:
     group 0
     group 1

Others:
     stuff 0
     stuff 1
```

**Comment by arzdou** [comment]
Closed with commit [b769c769c6e6bc0b143242d78fd6d67b355605f0](https://github.com/arzdou/botXiv/commit/b769c769c6e6bc0b143242d78fd6d67b355605f0)
